openapi: 3.0.3
info:
  title: Log Analyzer API
  version: 1.0.0
  description: An NginX log analyzer
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/v1/logs/:
    post:
      operationId: v1_logs_create
      tags:
      - v1
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LogFile'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogFile'
          description: ''
  /api/v1/logs/{id}/statistics:
    get:
      operationId: v1_logs_statistics_list
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NginxLog'
          description: ''
  /api/v1/logs/{id}:
    put:
      operationId: v1_logs_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LogFile'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogFile'
          description: ''
components:
  schemas:
    LogFile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          readOnly: true
        original_name:
          type: string
          readOnly: true
        file:
          type: string
          format: uri
        size:
          type: integer
          readOnly: true
        upload_date:
          type: string
          format: date-time
          readOnly: true
        head:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
      - file
      - id
      - name
      - original_name
      - size
      - upload_date
    NginxLog:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        ip_address:
          type: string
          maxLength: 32
        remote_user:
          type: string
          maxLength: 128
        date_time:
          type: string
          format: date-time
        request_method:
          type: string
          maxLength: 20
        request_url:
          type: string
        protocol:
          type: string
          maxLength: 20
        status_code:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        size_of_response_body:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        referrer_url:
          type: string
        user_agent:
          type: string
        log_file:
          type: integer
      required:
      - date_time
      - id
      - ip_address
      - log_file
      - protocol
      - referrer_url
      - remote_user
      - request_method
      - request_url
      - size_of_response_body
      - status_code
      - user_agent
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
