# Generated by Django 4.1.6 on 2023-09-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxlog',
            name='log_file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nginx_logs', to='logs.logfile'),
            preserve_default=False,
        ),
    ]
